# Generated by Django 5.0.2 on 2024-03-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_bloger_created_user_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_media',
            field=models.CharField(choices=[('instagram', 'Instagarm'), ('tik tok', 'Tik Tok'), ('telegram', 'Instagarm')], default='instagram', max_length=10),
            preserve_default=False,
        ),
    ]
