# Generated by Django 5.0.2 on 2024-03-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_social_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='social_media',
            field=models.CharField(blank=True, choices=[('instagram', 'Instagarm'), ('tik tok', 'Tik Tok'), ('telegram', 'Instagarm')], max_length=10, null=True),
        ),
    ]
