# Generated by Django 5.0.2 on 2024-03-03 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_user_social_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloger',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='main.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bloger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloger', to='main.bloger'),
        ),
    ]
